import time

user_name = input("Hello!, what is your name?: ")
time.sleep(1.5)
print(f"Hi {user_name} here are the instructions to cook pasta: ")
time.sleep(2.5)
print("First, you need to boil some water.")
time.sleep(2.5)
print("So, wait for about five minutes.")
time.sleep(2.5)
print("Then add a little bit of salt to the water.")
time.sleep(2.5)
print("And afterwards, add the pasta to the water.")
time.sleep(2.5)
print("Cook for approximately 10 minutes.")
time.sleep(2.5)
print("After the 10 minutes have passed, turn off the stove.")
time.sleep(2.5)
print("Then, pour the pot of pasta and water through a colander set in your sink to remove the water.")
time.sleep(2.5)
print("Finally, you're done! Enjoy your delicious pasta!")
